services:
  efm.api:
    image: ${DOCKER_REGISTRY-}efmapi
    container_name: EFM.Api
    build:
      context: .
      dockerfile: src/api/EFM.Api/Dockerfile
    ports:
    - "5000:8080"
    - "5001:8081"

  sqlserver: 
    image: mcr.microsoft.com/mssql/server:2022-latest 
    container_name: sqlserver_test 
    environment: 
        - ACCEPT_EULA=Y 
        - SA_PASSWORD=Password123! 
    ports: 
        - "1433:1433"